import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { Modal } from "~/components/modal";
import { Toaster } from "~/components/ui/sonner";
import { ModalProvider } from "~/context/ModalContext";
import { TRPCReactProvider } from "~/trpc/react";
import Navbar from "./_components/navbar";
import { ThemeProvider } from "./_components/theme-provider";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="h-screen">
        <SessionProvider>
          <TRPCReactProvider>
            <ThemeProvider attribute="class" enableSystem>
              <ModalProvider>
                <div className="flex h-full flex-col">
                  <Navbar />
                  <div className="flex h-full">
                    <div className="mx-auto h-full max-w-7xl flex-1 grow p-2">
                      {children}
                      <Modal />
                    </div>
                  </div>
                  <Toaster />
                </div>
              </ModalProvider>
            </ThemeProvider>
          </TRPCReactProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
